version: '3.9'

services:
  db:
    image: postgres:13.1-alpine
    volumes:
      - crm_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
  web:
    build: .
    command: python /usr/src/crm/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/crm
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  crm_postgres_data: